models/AddArticleForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class AddArticleForm extends \yii\base\Model {

    public $title;
    public $short_description;
    public $text;
    public $id;

    public function rules() {

        return [

            [['title', 'short_description', 'text'], 'required'],
            ['title', 'string', 'min' => 2, 'max' => 25],
            ['short_description', 'string', 'min' => 5, 'max' => 250],
            ['text', 'string', 'min' => 50],
            ['id', 'number'],
        ];

    }

}

models/Articles.php
<?php


namespace app\models;


use yii\db\ActiveRecord;

class Articles extends ActiveRecord
{

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AddArticleForm;
use app\models\Articles;
use Yii;
use yii\data\Pagination;
use yii\data\Sort;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //Get all Articles
        $query = Articles::find();

        // Config for sort widget
        $sort = new Sort([
            'attributes' => [
                'age',
                'title' => [
                    'asc' => ['title' => SORT_ASC],
                    'desc' => ['title' => SORT_DESC],
                    'default' => SORT_DESC,
                    'label' => 'title',
                ],
                'time' => [
                    'asc' => ['id' => SORT_ASC],
                    'desc' => ['id' => SORT_DESC],
                    'default' => SORT_DESC,
                    'label' => 'time',
                ],
            ],
        ]);

        // Config for Pagination
        $pagination = new Pagination([
        'defaultPageSize' => 6,
        'totalCount' => $query->count(),
        ]);

        //Getting Articles by params
        $articles = $query -> orderBy($sort->orders)
        -> offset($pagination->offset)
        -> limit ($pagination->limit)
        -> all();

        return $this->render('index', [
            'articles' => $articles,
            'pagination' => $pagination,
            'sort' => $sort,
            'message' => Yii::$app->request->get('message') ?: '',
            'message_type' => Yii::$app->request->get('message_type') ?: '',
        ]);
    }

    /**
     * Adding new Article
     * @return string|Response
     */
    public function actionAddArticle()
    {
        $form = new AddArticleForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate() ) {
            $article = new Articles();
            $article->title = $form->title;
            $article->short_description = $form->short_description;
            $article->text = $form->text;
            $article->save();

            return $this->redirect('index.php?message=adding the article successfully&message_type=success');

        } else {
            return $this->render('addArticle', ['model' => $form]);
        }
    }

    /**
     * Deleting Article by id
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDeleteArticle()
    {
        $request = Yii::$app->request;
        if ($request->get('id')){
            $query = Articles::findOne($request->get('id'));
            $query->delete();
            $this->redirect('index.php?message=deleting the article successfully&message_type=warning');
        } else {
            $this->redirect('index.php?message=the article not found&message_type=danger');
        }
    }

    /**
     * Editing Article
     * @return string|Response
     */
    public function actionEditArticle()
    {
        $form = new AddArticleForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate() ) {
            $article = Articles::findOne($form->id);
            $article->title = $form->title;
            $article->short_description = $form->short_description;
            $article->text = $form->text;
            $article->save();

            return $this->redirect('index.php?message=editing the article successfully&message_type=success');

        } elseif ($id = Yii::$app->request->get('id')) {
            $article = Articles::findOne(Yii::$app->request->get('id'));
            if (!$article) {
                $this->redirect('index.php?message=the article not found&message_type=danger');
            } else {
                $form->title = $article['title'];
                $form->short_description = $article['short_description'];
                $form->text = $article['text'];
                $form->id = $article['id'];

                return $this->render('editArticle', ['model' => $form]);
            }
        } else {
            $this->redirect('index.php?message=the article not found&message_type=danger');
        }
    }

    /**
     * Opening Article by id
     * @return string
     */
    public function actionArticle()
    {
        $request = Yii::$app->request;
        if ($request->get('id')){
            $article = Articles::findOne($request->get('id'));

            if ($article) {
                return $this->render('article', [
                    'article' => $article,
                ]);
            } else {
                $this->redirect('index.php?message=the article not found&message_type=danger');
            }
        } else {
            $this->redirect('index.php?message=the article not found&message_type=danger');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <a href="<?= Yii::$app->homeUrl ?>">
        <h1 class="text-center text-light bg-dark">List of articles:</h1>
    </a>
    <div class="d-flex justify-content-between">
        <a class="btn btn-lg btn-success " href="<?= Yii::$app->homeUrl ?>">Home</a>
        <a class="btn btn-lg btn-success " href="<?= Url::to(['site/add-article'])?>">Add new article</a>
    </div>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="d-flex justify-content-between">
        <p class=" ml-5">&copy; Neodimius <?= date('Y') ?></p>

        <p class="mr-5"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/addArticle.php
<?php
/* @var $this yii\web\View */

use mihaildev\ckeditor\CKEditor;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Add new article';
?>

<h1><?= $this->title ?></h1>

<?php $form = ActiveForm::begin([
    'method' => 'post',
    'options' => ['enctype' => 'multipart/form-data'],
    'action' => Url::to(['site/add-article']),
]) ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'short_description')->textarea(array('rows'=>3,'cols'=>5)) ?>
<?= $form->field($model, 'text')->widget(CKEditor::className(),[
    'editorOptions' => [
        'preset' => 'basic', //basic, standart or full
        'inline' => false,
        'height' => 500,
    ],]); ?>

<?= Html::submitButton('Add article', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

views/site/article.php
<?php

/* @var $this yii\web\View */

$this->title = $article['title'];

use yii\helpers\Url;
use yii\web\View; ?>
<div class="site-index">
    <div class="jumbotron">
        <h1 class="display-4"><?= $this->title; ?></h1>
        <hr class="my-4">
        <a href="<?= Url::to(['site/edit-article']) . '&id=' . $article['id']; ?>" class="btn btn-warning">Edit</a>
        <a href="<?= Url::to(['site/delete-article']) . '&id=' . $article['id']; ?>" class="btn btn-danger">Delete</a>
    </div>
    <p class="text-justify"><?= $article['text']; ?></p>
</div>

views/site/editArticle.php
<?php
/* @var $this yii\web\View */

use yii\web\View;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use mihaildev\ckeditor\CKEditor;

$this->title = 'Edit article';
?>

<h1><?= $this->title ?></h1>

<?php $form = ActiveForm::begin([
    'method' => 'post',
    'options' => ['enctype' => 'multipart/form-data'],
    'action' => Url::to(['site/edit-article']),
]) ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'short_description')->textarea(array('rows'=>3,'cols'=>5)) ?>
<?= $form->field($model, 'text')->widget(CKEditor::className(),[
    'editorOptions' => [
        'preset' => 'basic', //basic, standart or full
        'inline' => false,
        'height' => 500,
    ],]); ?>
<?= $form->field($model, 'id')->hiddenInput()->label(false) ?>

<?= Html::submitButton('Edit article', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'List of Articles';

use yii\helpers\Url; ?>
<div class="site-index">
    <?php if (!empty($message)) :?>
        <div class="alert alert-<?= $message_type; ?>" role="alert">
            <?= $message; ?>
        </div>
    <?php endif; ?>

    <?php echo \yii\bootstrap4\LinkPager::widget([
        'pagination' => $pagination,
    ]);?>

    <div class="bg-dark">
        <span class="text-light">Sort by: </span>
        <!--    Sort by:-->
        <?php echo $sort->link('title') . ' | ' . $sort->link('time'); ?>
    </div>

    <div class="d-flex justify-content-between flex-wrap">
        <?php foreach ($articles as $article):?>
            <div class="card border-dark mb-3" style="width: 18rem;">
                <div class="card-header d-flex justify-content-between">
                    <a href="<?= Url::to(['site/edit-article']) . '&id=' . $article['id']; ?>" class="btn btn-warning">Edit</a>
                    <a href="<?= Url::to(['site/delete-article']) . '&id=' . $article['id']; ?>" class="btn btn-danger">Delete</a>
                </div>
                <div class="card-body text-dark">
                    <h5 class="card-title"><?= $article['title'] ?></h5>
                    <p class="card-text"><?= $article['short_description'] ?></p>
                    <a href="<?= Url::to(['site/article']) . '&id=' . $article['id']; ?>" class="btn btn-primary">Read more</a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php echo \yii\bootstrap4\LinkPager::widget([
        'pagination' => $pagination,
    ]);?>
</div>